dateModified: 1739198088
email:
  fromEmail: odanilevskaya2@gmail.com
  fromName: cyf
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4d801593-02bf-4b7a-ae63-0e1e845bf06a: cyf # cyf
    023b397b-1a6c-4bbe-b4d9-84eb171acf07: cyf # cyf
system:
  edition: solo
  live: true
  name: cyf
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
